package com.comicread.android.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.comicread.android.data.ComicBean;

import com.comicread.android.db.ComicBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicBeanDaoConfig;

    private final ComicBeanDao comicBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicBeanDaoConfig = daoConfigMap.get(ComicBeanDao.class).clone();
        comicBeanDaoConfig.initIdentityScope(type);

        comicBeanDao = new ComicBeanDao(comicBeanDaoConfig, this);

        registerDao(ComicBean.class, comicBeanDao);
    }
    
    public void clear() {
        comicBeanDaoConfig.clearIdentityScope();
    }

    public ComicBeanDao getComicBeanDao() {
        return comicBeanDao;
    }

}
